"""add unique constraint to productions.title

Revision ID: 40071812dca5
Revises: 3c55cfc31ba3
Create Date: 2024-09-19 10:54:28.792663

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = "40071812dca5"
down_revision = "3c55cfc31ba3"
branch_labels = None
depends_on = None

conn = op.get_bind()
inspector = inspect(conn)  # type: ignore

# Check if the temporary table exists and drop it if it does
if inspector.has_table("_alembic_tmp_productions"):
    op.execute("DROP TABLE _alembic_tmp_productions")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("productions", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["title"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("productions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
