"""add ongoing to productions

Revision ID: b6018a6499ca
Revises: ec9c48bab540
Create Date: 2024-09-13 11:47:58.450314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6018a6499ca'
down_revision = 'ec9c48bab540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productions', sa.Column('ongoing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productions', 'ongoing')
    # ### end Alembic commands ###
